/* exporters/tacz.js
 * メタ＋Bedrockジオメトリ から TaCZ(Timeless and Classics: Zero, 1.20.1 Forge)
 * のガンパック一式を生成する。ユーザー作成パック形式（フラットなnamespaceフォルダ）。
 *
 * 返り値: { files:[{path,text}], uvPath, slotPath, readme, zipName }
 *
 * 注: モデルテクスチャ(uv)とスロットアイコン(slot)は同じパレットPNGを流用。
 *     ammoは内蔵弾を参照（idはバージョン差あり→READMEで要確認と明記）。
 */
function buildTaczPack(meta, ctx, geoJson) {
  const ns = ctx.namespace, id = ctx.itemId;
  const name = meta.displayName || id;
  const files = [];

  files.push({ path: `${ns}/pack.json`, text: JSON.stringify({
    version: '1',
    name: `pack.${ns}.name`,
    desc: `pack.${ns}.desc`,
    license: 'All Rights Reserved',
    author: ['Natane Voxel & Data Forge'],
  }, null, 2) });

  files.push({ path: `${ns}/guns/index/${id}.json`, text: JSON.stringify({
    name: `${ns}.gun.${id}.name`,
    display: `${ns}:${id}_display`,
    data: `${ns}:${id}_data`,
    type: 'rifle',
    item_type: 'modern_kinetic',
    sort: 10,
  }, null, 2) });

  files.push({ path: `${ns}/guns/data/${id}_data.json`, text: JSON.stringify({
    ammo: 'tacz:ammo_762x39',           // ★内蔵弾。F3+Hでidを確認し必要なら変更
    ammo_amount: meta.stats.magazine || 30,
    bolt: 'closed_bolt',
    rpm: 600,
    bullet: {
      life: 10,
      damage: meta.stats.attack || 6,
      speed: meta.stats.range ? meta.stats.range * 20 : 400,
      gravity: 0,
      knockback: 0,
      pierce: 1,
    },
    reload: {
      type: 'magazine',
      feed: { empty: (meta.stats.reloadTime || 2.5), tactical: (meta.stats.reloadTime || 2.0) },
      cooldown: { empty: (meta.stats.reloadTime || 2.6), tactical: (meta.stats.reloadTime || 2.0) },
    },
    draw_time: 0.35,
    aim_time: 0.2,
    sprint_time: 0.3,
    fire_mode: ['semi', 'auto'],
    recoil: {
      pitch: [{ time: 0, value: [0.7, 0.7] }, { time: 0.25, value: [0.7, 0.7] }, { time: 0.5, value: [0, 0] }],
      yaw: [{ time: 0, value: [-0.3, 0.3] }, { time: 0.25, value: [-0.3, 0.3] }, { time: 0.5, value: [0, 0] }],
    },
    inaccuracy: { stand: 2, move: 4, sneak: 1, lie: 0.5, aim: 0.2 },
  }, null, 2) });

  files.push({ path: `${ns}/guns/display/${id}_display.json`, text: JSON.stringify({
    model: `${ns}:gun/${id}_geo`,
    texture: `${ns}:gun/uv/${id}`,
    slot: `${ns}:gun/slot/${id}`,
    use_default_animation: 'rifle',     // 内蔵アニメで補完→独自アニメ不要
    third_person_animation: 'default',
  }, null, 2) });

  files.push({ path: `${ns}/models/gun/${id}_geo.json`, text: JSON.stringify(geoJson, null, 2) });

  // レシピ（TaCZ独自形式・Gun Smith Table）
  if (['crafting', 'both'].includes(meta.acquisition.method)) {
    const counts = {};
    meta.acquisition.crafting.grid.forEach(s => { const k = (s || '').trim(); if (k) counts[k] = (counts[k] || 0) + 1; });
    const materials = Object.entries(counts).map(([item, count]) => ({ item: { item }, count }));
    if (materials.length) {
      files.push({ path: `${ns}/recipes/gun/${id}.json`, text: JSON.stringify({
        materials, result: { type: 'gun', id: `${ns}:${id}` },
      }, null, 2) });
    }
  }

  files.push({ path: `${ns}/lang/en_us.json`, text: JSON.stringify({
    [`pack.${ns}.name`]: name + ' Pack',
    [`pack.${ns}.desc`]: 'Generated by Natane Voxel & Data Forge',
    [`${ns}.gun.${id}.name`]: name,
  }, null, 2) });

  const readme = [
    'TaCZ ガンパック — 導入方法',
    '',
    '1. 必要Mod: Timeless and Classics: Zero (TaCZ, 1.20.1 Forge)。',
    '2. このZIPを .minecraft/tacz/ に置く（TaCZ 1.1.4+。解凍しない）',
    '   または中身を config/tacz/custom/<任意名>/ に展開。',
    '3. ゲーム内で /tacz reload。',
    '',
    '★注意:',
    `- 使用弾は "tacz:ammo_762x39" を仮指定しています。F3+H(高度ツールチップ)で`,
    '  実際の弾idを確認し、guns/data/' + id + '_data.json の "ammo" を必要に応じ変更。',
    '- uv/slot テクスチャはパレット画像を流用しています(簡易)。差し替え推奨。',
    '- 銃の見た目はボクセル形状。3人称アニメ等は内蔵(use_default_animation)で補完。',
  ].join('\n');

  return {
    files,
    uvPath: `${ns}/textures/gun/uv/${id}.png`,
    slotPath: `${ns}/textures/gun/slot/${id}.png`,
    readme,
    zipName: `${id}_tacz.zip`,
  };
}
